name: Build and Deploy Site

on:
  push:
    branches:
      - master 

jobs:
  build:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs Setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
