name: Build and Deploy Site

on:
  push:
    branches:
      - master 

jobs:
  build:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs Setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'DaniyarIrkagaliev'
          git config --global user.email 'Daniyar_Irkagaliev@mail.ru'
          git add .
          git commit -m "Deploying to GitHub Pages"
          git push origin main
